[build]
target = "x86_64-pc-windows-msvc"

[target]

[target.aarch64-linux-android]
#rustc-link-search = "E:\\AndroidSDK\\ndk\\28.0.12433566\\toolchains\\llvm\\prebuilt\\windows-x86_64\\sysroot\\usr\\lib\\aarch64-linux-android"
#rustc-link-lib = [
#    "libc++",
#    "libc++abi",
#    "libdl",
#    "libm",
#    "libz",
#    "libc++_static",
#    "libc++experimental",
#    "libcompiler_rt-extras",
#]
rustflags = [
    "-L", "native=E:\\AndroidSDK\\ndk\\28.0.12433566\\toolchains\\llvm\\prebuilt\\windows-x86_64\\sysroot\\usr\\lib\\aarch64-linux-android",
    "-l", "static=c++",
    "-l", "static=c++abi",
    "-l", "static=dl",
    "-l", "static=m",
    "-l", "static=z",
    "-l", "static=compiler_rt-extras",
    "-l", "static=c++experimental",
    "-l", "static=c++_static",
]
